### ISSUE TITLE
help！！！ lucon 

### ISSUE THREAD

**Issue by liuhaichaogithub** [industrial-data-space/trusted-connector#158]
https://ids.aisec.fraunhofer.de/eclipse  Can not access web pages  and i need lucon documnet, thanks

**Comment by milux** [comment]
What do you mean by "LUCON document"?
Research papers about LUCON have been published online.
WHAT do you even need it FOR? The original LUCON implementation was always about local flow control and not extended to Usage Control across system boundaries. Development of that implementation has effectively stopped several years ago.

**Comment by spetrac** [comment]
@liuhaichaogithub Is this really an issue with this trusted-connector repository? If yes, could you specify your problem in detail, otherwise I think this is not the right place to put personal request.

**Comment by milux** [comment]
Thanks @spetrac, but we already sorted this out. We're going to upload the old plugin source in a separate repo here, for reference, soon: https://github.com/Fraunhofer-AISEC/lucon-plugin
There will however not be any support or anything of that kind for this for the reasons stated above.
