### ISSUE TITLE
Base connector vs trusted connector

### ISSUE THREAD

**Issue by imonbayazid** [industrial-data-space/trusted-connector#16]
I was exploring the codes of trusted connector. However, a few questions popped into my mind: 

1. Is there a link or dependency between a base and a trusted connector? 
2. It is not clear to me the role of a base connector in the trusted connector. 

Could some clarify these. please?

Thanks

**Comment by gbrost** [comment]
In the IDS, three certification profiles are defined: Base, Trust, Trust+.
For base and trust, we have several reference implementations, as linked by oxisto in the closed issue. 
The Trusted Connector stack is not related to other imlementations besides some compatibility. What company or institution are you from?

**Comment by milux** [comment]
I close this one due to inactivity.
