### ISSUE TITLE
Source of  the base connector

### ISSUE THREAD

**Issue by imonbayazid** [industrial-data-space/trusted-connector#18]
_Base connector_ of _Industrial Data Space_ used docker image. I was trying to find the source code of the base connector but unable to find. 
Can you please give the explanation regarding the source code of the base connector and also where can i get the source ?

Thanks in Advance

**Comment by gbrost** [comment]
Sorry, this is not a valid issue for this project. This is the Trusted Connector project. 
What is the "Base Connector" in your opinion? There is some instances of it like the simple connector from our colleagues from Fraunhofer ISST.

**Comment by oxisto** [comment]
You can find an overview of all connector implementations at https://www.dataspaces.fraunhofer.de/en/software/connector.html.
