### ISSUE TITLE
DefaultDapsDriver vs TokenManagerService

### ISSUE THREAD

**Issue by oxisto** [industrial-data-space/trusted-connector#20]
The `de.fhg.aisec.ids.idscp2.drivers.default_driver_impl.daps.DefaultDapsDriver` seems to duplicate functionality of `de.fhg.aisec.ids.tokenmanager.TokenManagerService` - except that the DefaultDapsDriver seems to use the "old" DAPS token endpoint - which seems to fail.

**Comment by milux** [comment]
Correct. We need to change this to a binding between those modules. It doesn't make sense that this functionality is duplicated.
