### ISSUE TITLE
Message headers not sent through IDS protocol

### ISSUE THREAD

**Issue by rizktouma** [industrial-data-space/trusted-connector#23]
**Describe the bug**
When executing the `examples/example-idscp` following the provided instructions, the headers that the message has on the provider side (in this case, coming from the MQTT broker) are not being sent through the IDS connector to the consumer side.

**To Reproduce**
1. Go to 'https://industrial-data-space.github.io/trusted-connector-documentation/docs/rest/' and follow the steps to download the example files.
2. Modify the `example-provider-routes.xml` and `example-consumer-routes.xml` files to log the headers of the message along with the body by adding `${headers}` to the `<log message="... "/>` element.
3. Run the docker-compose commands as explained in the documentation above.
4. Once the communication between provider and consumer is established, open the log file and notice that the headers printed on the provider side do not appear when the message gets to the consumer.

**Expected behavior**
I expect the message headers on the provider side to be sent to the consumer through the IDS connector along with the message body.

**Screenshots and logs**
Attached is an example log file where this issue appears (e.g. difference in headers between lines 1868 and 1904)
[karaf.log](https://github.com/industrial-data-space/trusted-connector/files/5256518/karaf.log)

**Environment (please complete the following information):**
 - OS: Docker container
 - Environment: Docker Desktop
 - Version [commit hash]

**Additional context**
The problem seems to stem from `WebSocketProvider.java` and `WebSocketConsumer.java` in the `camel-ids/src/main/java/de/fhg/aisec/ids/camel/ids/server` directory, which do not send any headers but only the message body. In the absence of this, do you recommend any other way to differentiate between messages received from the IDS connector by the consumer? For further context, we want to apply conditional routing using Camel from the consumer IDS connector to multiple endpoints in the consumer app API.

**Comment by gbrost** [comment]
Thank you for you very well structured issue report. Indeed, this works as designed so far. Did you have the chance to look at IDSCPv2? [Here](https://industrial-data-space.github.io/trusted-connector-documentation/docs/using_idscpv2/) is some tutorial content. Using the v2, you have the option to set dedicated headers. 
In the meanwhile, we are working on an application layer that allows for more distinct use case coverage. This is still incomplete, yet...

**Comment by rizktouma** [comment]
Thank you for the answer I have indeed taken a look at IDSCPv2. Is there a ready docker image to use this version of IDSCP? If not, is it possible to summarize the changes needed to modify the trusted-connector-core image to include IDSCPv2 instead of IDSCP? Or would that require too much work?

**Comment by gbrost** [comment]
It is supported ouf of the box. If you write idscp2 routes, you should be fine...
