### ISSUE TITLE
Setting up a broadcasting provider server (IDSCPv2) not behaving as expected

### ISSUE THREAD

**Issue by rizktouma** [industrial-data-space/trusted-connector#25]
**Describe the bug**
The IDSCPv2 examples include some route examples to do a broadcast, where the consumer is the broadcasting server and the provider is the receiving client. We need to do it the other way around, with a broadcasting provider server sending messages to all of its connected client consumers.

So I added the following route to the provider routes (we have a separate data generator publishing messages into the `forklift/+/position` MQTT topic):

```
  <route id="idscp2SenderServer">
    <from uri="paho:forklift/+/position?brokerUrl=tcp://mqtt-broker:1883"/>
    <convertBodyTo type="java.lang.byte[]" charset="utf-16"/>
    <setHeader name="idscp2-header">
		<simple>${header.CamelMqttTopic}</simple>
    </setHeader>
    <log message="Server broadcast to connected clients: ${body} ${headers}"/>
    <to uri="idscp2server://0.0.0.0:29292?sslContextParameters=#serverSslContext"/>
  </route>
```

and the following route to the consumer routes (where `forkliftPosition` is defined as a `camel-cxf:cxfEndpoint`):

```
  <route id="idscp2Client">
    <from uri="idscp2client://provider-core:29292?sslContextParameters=#clientSslContext"/>
    <log message="Client received: ${body} ${headers}"/>
    <to uri="forkliftPosition"/>
  </route>
```

When the provider is started at first, the log correctly contains the messages from the server route. However, when the consumer is started and tries to connect to the server, the logs of both the consumer and provider show these messages and do not progress anymore:

```
ForkJoinPool.commonPool-worker-5 | DefaultDapsDriver                | 57 - idscp2 - 1.0.0 | Retrieving Dynamic Attribute Token...
ForkJoinPool.commonPool-worker-5 | DefaultDapsDriver                | 57 - idscp2 - 1.0.0 | Acquire DAT from https://daps.aisec.fraunhofer.de
```
The provider route is then stopped because of a timeout and the messages never reach the conusmer.

**To Reproduce**
1. Clone the repository
2. Change the consumer and provider routes in the IDSCPv2 examples to include the routes mentioned above. You also need to change the names of the `clientSslContext` and `serverSslContext` defined in the provider and consumer routes respectively.
3. Start the TTP, Provider and Consumer docker containers

**Expected behavior**
The messages should be broadcast to all connected clients (in this case one).

**Screenshots and logs**
[provider-karaf.log](https://github.com/industrial-data-space/trusted-connector/files/5464036/provider-karaf.log) (connection details: line 2448)
[consumer-karaf.log](https://github.com/industrial-data-space/trusted-connector/files/5464037/consumer-karaf.log) (connection details: line 1288)

Note: In our use case, we are sending the messages as a byte array so the messages shown in the provider logs will contain weird characters as they are not strings.

**Environment (please complete the following information):**
 - OS: Docker Desktop on Windows 10 x64
 - Environment: Docker Desktop
 - Version: 26ec8c8

**Additional context**
In all of the examples included in the repository, both with IDSCPv1 and IDSCPv2, the consumer is treated as a "server" and the provider as a "client". Is there a specific reason for that? Can we just switch them so that the provider is the server (in particular in this case a broadcasting server) and the consumer(s) is the client(s)? For further context, we want the provider to send the same messages to all connected consumers, without having to specify the endpoint of each consumer client separately in the provider routes as is done with the non-broadcasting IDSCPv2 example routes (`example-idscp2-client.xml`).

**Comment by milux** [comment]
Regarding the server/client naming: No, there's no specific reason. That actually doesn't even make sense in our broadcast example, because it is technically identical to what you have done. I missed to rename some files when constructing the broadcast example from the other one, that's the only reason. I just fixed this for develop.

Regarding the issue itself:
I can't see anything wrong in your work, so I assume that this is a connectivity issue, maybe some weird firewall is blocking or delaying the connection to the DAPS? To confirm this hypothesis, you may start our "plain" broadcast example with the new, dedicated YAML files I just created. This is working without any issues here on my machine.

**Comment by gbrost** [comment]
If you did like milux said and you keep getting DAPS connectivity issues, i can provide you with a script to test token retrieval...

**Comment by rizktouma** [comment]
I just tried the new examples as well as my code and it worked without making any changes. It must've been a temporary issue with the token retrieval.
Thanks for looking into this and uploading the new examples.
