### ISSUE TITLE
Usage Control Tutorial

### ISSUE THREAD

**Issue by musi00** [industrial-data-space/trusted-connector#38]
Hello,

I tried to follow the usage control tutorial outlined here: https://industrial-data-space.github.io/trusted-connector-documentation/docs/usage_control/

I installed Eclipse and the Lucon Editor.  However, when I created a lucon policy it did not automatically generate a .pl file.  I'm not sure how to generate the .pl file.  Please see screenshot below:
![image](https://user-images.githubusercontent.com/5386051/113776178-9ffa4680-96f7-11eb-86a2-a770071be211.png)

A second issue is that the tutorial does not explain how to use the generated .pl file.  My guess is that it goes into the deploy dir of the docker container of the trusted connector core.  Can you please confirm

**Comment by gbrost** [comment]
Hi, 
to be honest, we are currently in a phase where we totally redesign LUCON. Currently, the really working part is this:
https://industrial-data-space.github.io/trusted-connector-documentation/docs/using_idscpv2/
We are moving away from a DSL towards the general IDS Contract agreement scheme. 
This is yet incomplete, so just one example policy is supported right now, as listed in the idscpv2 tutorial.
