### ISSUE TITLE
Connect an embedded IDS protocol client to an existing trusted connector server 

### ISSUE THREAD

**Issue by spicoflorin** [industrial-data-space/trusted-connector#39]
Hello!
 I would like to know how can I create a client that is using the embedded IDS protocol to connect to an existing trusted connector that has not incorporated the embedded IDS protocol.
Here is my scenario:
I would like to combine:
1. The example server consumer server from 
https://industrial-data-space.github.io/trusted-connector-documentation/docs/rest/
2. with a data provider (client) created as mentioned in 
https://industrial-data-space.github.io/trusted-connector-documentation/docs/idscp/
and implemented by
https://github.com/industrial-data-space/ids-comm-example

I have configured the client 
` IdscpClient client = new IdscpClient().config(
                new ClientConfiguration.Builder()
                        .setSha256CertificateHashes(Arrays.asList(
                                // test localhost certificate
                                DatatypeConverter.parseHexBinary(
                                        "A3374C859BD5E819B5B50486040FB2DCEA5EC4E3F04DDBC3D059E162B8B7AB37"),
                                // example consumer-core certificate
                                DatatypeConverter.parseHexBinary(
                                        "D2474D41B96B5F5EA499CE42176C2D4C466DBE5F60C1DF07F646B576F5CBB04C")))
                        .build());
`

but when the  connection is performed by the client, the server throws the following exceptions:
`
![image](https://user-images.githubusercontent.com/4939817/114883336-82bb2b80-9e0d-11eb-9917-014162420f28.png)
`
My question is:
How can I implement the client in order to properly connect to the existing trusted connector?

Thanks.
 Florin

**Comment by milux** [comment]
Hello Florin,
IDSCP version 1 is deprecated and has been finally removed with TC 4.0.0.
Please switch to the recent IDSCP2 protocol, you can find examples and everything else in the TC sources and the `idscp2-java` project: https://github.com/industrial-data-space/idscp2-java
