### ISSUE TITLE
OSGiless: Automatically load camel routes from XML files in a specific directory

### ISSUE THREAD

**Issue by oxisto** [industrial-data-space/trusted-connector#42]
Similar to what we had in the `deploy` folder in OSGi.

**Comment by oxisto** [comment]
According @milux it is also possible to specify the whole camel *context*, not just the routes.

**Comment by milux** [comment]
https://www.baeldung.com/spring-apache-camel-tutorial

**Comment by oxisto** [comment]
It seems Spring will provide us with the loading mechanism. We need to implement loading at startup and file watching.
