### ISSUE TITLE
OSGiless: Fix REST authentication and related stuff

### ISSUE THREAD

**Issue by oxisto** [industrial-data-space/trusted-connector#43]
It may be related to the settings database.

**Comment by milux** [comment]
All REST endpoints seem to work, however, **authentication is broken** since the relevant components are not wired anymore.

**Comment by milux** [comment]
Turns out that I was wrong, components seem to work just fine, Spring Boot magic... :mage: 
However, we still need proper Auth via database or something, currently there's only the hardcoded `ids:ids` login, which is menat for debugging only...

**Comment by milux** [comment]
User database (MapDB HashMap) with argon2id password hashing implemented.
Controllable via REST interface.
