### ISSUE TITLE
OSGiless: Deadlock in IDSCP2 example

### ISSUE THREAD

**Issue by oxisto** [industrial-data-space/trusted-connector#48]
Seems that server and client both try to access the DAPS token at the same time and run into a deadlock.

**Comment by milux** [comment]
Fixed! Has been caused by weird downgrading of OkHttp to version 3.x.
Example now runnable on localhost, given the following `/etc/hosts` entries:
```
127.0.0.1	consumer-core
127.0.0.1	provider-core
```

**Comment by milux** [comment]
> Shouldn't it work without the entries as well? the certificates I used for the example were using `127.0.0.1` / `localhost` instead of the fake hostname.

Yes, but that requires changes to the (Dev) DAPS configuration.
