### ISSUE TITLE
Problem with Mosquitto integration in Camel

### ISSUE THREAD

**Issue by alzcurda** [industrial-data-space/trusted-connector#63]
**Describe the bug**
We were using Mosquitto with Camel using Karaf. In the last version of trusted-connector it changed to Spring and we aren't able to configure Mosquitto.

**To Reproduce**
Using the examples of the connector, we added to file "example-idscp2-server-broadcast.xml" 
the next code:

```
<camelContext xmlns="http://camel.apache.org/schema/spring">
		<route id="broadcastForkliftPosition">
			<from uri="paho:forklift/+/position?brokerUrl=tcp://mqtt-broker:1883"/>
			<convertBodyTo type="java.lang.byte[]" charset="utf-16"/>
			<setHeader name="idscp2-header">
				<simple>${header.CamelMqttTopic}</simple>
			</setHeader>
			<log message="Server broadcast to connected clients: ${body} (Header: ${headers[idscp2-header]})"/>
			<to uri="idscp2server://0.0.0.0:29292?sslContextParameters=#serverSslContext"/>
		</route>
```

Now, with the Connector's last version, whe obtained this error:
`
2021-06-09 14:48:52.500 ERROR 1 --- [onPool-worker-3] o.a.camel.spring.SpringCamelContext : Error starting CamelContext (camel-2) due to exception thrown: Failed to create route broadcastForkliftPosition: Route(broadcastForkliftPosition)[From[paho:forklift/+/positi... because of Failed to resolve endpoint: paho://forklift/+/position?brokerUrl=tcp%3A%2F%2Fmqtt-broker%3A1883 due to: Cannot auto create component: paho
`

**Expected behavior**
We want to know if exists a way to install Eclipse Paho package as appears in the Developer documentacion:
https://industrial-data-space.github.io/trusted-connector-documentation/docs/dev_core/

In this documentation code you are using Karaf, but in the code you are using Spring instead.

**Environment (please complete the following information):**
 - OS:  64bit
 - Environment: Docker v20.10.6, Java 11.1, running on docker
 - Version trusted-connector 1.3.4

Thank you very much.

**Comment by milux** [comment]
As the log suggests, the feature is not included into our default distribution.
There are two ways to use `camel-paho`:

* Option 1: Fork the connector, add `camel-paho` (https://mvnrepository.com/artifact/org.apache.camel/camel-paho/3.0.1) as a implementation dependency, and rebuild.
* Option 2: Grab the JAR of the right version of `camel-paho` (https://mvnrepository.com/artifact/org.apache.camel/camel-paho/3.0.1) and all its transitive dependencies (seems to be only this one: https://mvnrepository.com/artifact/org.eclipse.paho/org.eclipse.paho.client.mqttv3/1.2.5) and mount them to `/root/jars` inside the core container by modifying the respective `docker-compose.yaml`.

Please report back if this doesn't work.
