### ISSUE TITLE
Unavailable management console when building the core platform

### ISSUE THREAD

**Issue by jfernandezsqs** [industrial-data-space/trusted-connector#64]
**Describe the bug**
Unavailable management console when building the core platform. 
I am not able to execute the command for making available the management console.
                karaf-assembly/build/assembly/bin/karaf clean debug

**To Reproduce**
1. Go to https://industrial-data-space.github.io/trusted-connector-documentation/docs/dev_core
    At the section Building the Core Platform in the subsection Build
    After a successful build I tried the command:
          karaf-assembly/build/assembly/bin/karaf clean debug

**Expected behavior**
The command should be successfully executed and the management console should be available.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04
 - Environment:
          Docker version 19.03.8
          Docker-compose version 1.25.0
          Java version 11.0.11
 - Version trusted connector 5.0.0

**Comment by milux** [comment]
The recent version of the connector is not based on karaf anymore, so there is no such thing as karaf-assembly anymore starting from 5.0.0.
Documentation is heavily outdated and going to be updated soon.
Meanwhile, please run `./gradlew :ids-connector:bootRun` to start the container, or use the `Dockerfile` within `ids-connector` to create a custom Docker image after running `./gradlew :ids-connector:build`.
