### ISSUE TITLE
Exception occurred during requesting DAT from DAPS

### ISSUE THREAD

**Issue by alzcurda** [industrial-data-space/trusted-connector#67]
**Describe the bug**

We are trying to reproduce the broadcast example. We tried with the latest version of trusted-conector and with de 4.0.0 version.

We can launch server but when we try launch client it always fail*.

*It worked since last Thursday (10/06/2021). It started failing on Friday without changing any code, software or hardware.
Can it be related with this past [issue](https://github.com/industrial-data-space/trusted-connector/issues/25)? It seems is a problem that appears out of nowhere.

**To Reproduce**
1. You can use the latest version or 4.0.0.
2. Launch server using:
docker-compose -f ./examples/example-idscp2/docker-compose-broadcast-server.yaml up --build
3. Launch client:
docker-compose -f ./examples/example-idscp2/docker-compose-broadcast-client.yaml up --build

**Expected behavior**
Server will broadcast correctly (it is ok):
provider-core_1  | 2021-06-11 19:15:58.703  INFO 1 --- [tenSecondsTimer] idscp2Server                             : Server broadcast to connected clients: BROADCAST (Header: broadcast)

Client will receive the message (it is failing).

**Screenshots and logs**
```
consumer-core_1  | 2021-06-11 19:09:05.870 ERROR 1 --- [onPool-worker-9] d.f.a.i.i.d.d.a.AisecDapsDriver          : Failed to request token issued with parameters: Issuer: A5:0C:A5:F0:84:D9:90:BB:BC:D9:57:3A:04:C8:7F:93:ED:97:A2:52:
keyid:CB:8C:C7:B6:85:79:A8:23:A6:CB:15:AB:17:50:2F:E6:65:43:5D:E8, Subject: A5:0C:A5:F0:84:D9:90:BB:BC:D9:57:3A:04:C8:7F:93:ED:97:A2:52:keyid:CB:8C:C7:B6:85:79:A8:23:A6:CB:15:AB:17:50:2F:E6:65:43:5D:E8, Expiration: Sat Jun 12 19:09:
05 GMT 2021, IssuedAt: Fri Jun 11 19:09:05 GMT 2021, NotBefore: Fri Jun 11 19:09:05 GMT 2021, Audience: idsc:IDS_CONNECTORS_ALL
consumer-core_1  | 2021-06-11 19:09:05.875 ERROR 1 --- [onPool-worker-9] d.f.aisec.ids.idscp2.idscp_core.fsm.FSM  : Exception occurred during requesting DAT from DAPS:
consumer-core_1  |
consumer-core_1  | de.fhg.aisec.ids.idscp2.idscp_core.error.DatException: Received non-200 http response: 400
consumer-core_1  |      at de.fhg.aisec.ids.idscp2.default_drivers.daps.aisec_daps.AisecDapsDriver.syncGetToken(AisecDapsDriver.kt:229) ~[idscp2-0.4.3.jar:na]
consumer-core_1  |      at de.fhg.aisec.ids.idscp2.default_drivers.daps.aisec_daps.AisecDapsDriver.getToken(AisecDapsDriver.kt:271) ~[idscp2-0.4.3.jar:na]
consumer-core_1  |      at de.fhg.aisec.ids.idscp2.idscp_core.fsm.FSM.getDynamicAttributeToken(FSM.kt:508) ~[idscp2-0.4.3.jar:na]
consumer-core_1  |      at de.fhg.aisec.ids.idscp2.idscp_core.fsm.StateClosed$1.invoke(StateClosed.kt:87) ~[idscp2-0.4.3.jar:na]
consumer-core_1  |      at de.fhg.aisec.ids.idscp2.idscp_core.fsm.StateClosed$1.invoke(StateClosed.kt:42) ~[idscp2-0.4.3.jar:na]
consumer-core_1  |      at de.fhg.aisec.ids.idscp2.idscp_core.fsm.Transition.doTransition(Transition.kt:30) ~[idscp2-0.4.3.jar:na]
consumer-core_1  |      at de.fhg.aisec.ids.idscp2.idscp_core.fsm.State.feedEvent(State.kt:46) ~[idscp2-0.4.3.jar:na]
consumer-core_1  |      at de.fhg.aisec.ids.idscp2.idscp_core.fsm.FSM.feedEvent(FSM.kt:369) ~[idscp2-0.4.3.jar:na]
consumer-core_1  |      at de.fhg.aisec.ids.idscp2.idscp_core.fsm.FSM.onControlMessage(FSM.kt:272) ~[idscp2-0.4.3.jar:na]
consumer-core_1  |      at de.fhg.aisec.ids.idscp2.idscp_core.fsm.FSM.startIdscpHandshake(FSM.kt:409) ~[idscp2-0.4.3.jar:na]
consumer-core_1  |      at de.fhg.aisec.ids.idscp2.idscp_core.fsm.AsyncIdscp2Factory$initiateIdscp2Connection$1.run(AsyncIdscp2Factory.kt:77) ~[idscp2-0.4.3.jar:na]
consumer-core_1  |      at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736) ~[na:na]
consumer-core_1  |      at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1728) ~[na:na]
consumer-core_1  |      at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290) ~[na:na]
consumer-core_1  |      at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020) ~[na:na]
consumer-core_1  |      at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656) ~[na:na]
consumer-core_1  |      at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594) ~[na:na]
consumer-core_1  |      at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183) ~[na:na]

```

**Environment (please complete the following information):**
 - OS: Docker Desktop on Windows 10 x64
 - Environment: Docker Desktop
 - Version [7ccb11b](https://github.com/industrial-data-space/trusted-connector/commit/7ccb11b187d9ba15206e56120e3c3b4c4ce58b4d)

**Comment by milux** [comment]
Works perfectly fine here, cannot reproduce.
Can you please make sure that you're using the latest version by doing `docker-compose -f ./examples/example-idscp2/docker-compose-broadcast-server.yaml pull` first?
BTW: The `--build` won't have any effect for these examples, since no build context is provided in the YAML files.

**Comment by alzcurda** [comment]
We have updated to the latest docke image and indeed it works now. However, 2 weeks ago when we opened the issue it seems that DAPS was down and the connector could not manage to get the tokens. This is not the first time that DAPS stops working temporarily, we opened a similar issue a few months ago (issue https://github.com/industrial-data-space/trusted-connector/issues/25).

The `--build` was carried over from our application launch where we do need to build some images locally.

Thanks for all.

**Comment by milux** [comment]
Theoretically, our DAPS is not meant for productive purposes still.
However, since more and more people rely on it anyway, we have started to employ rigid monitoring and reduce downtime on the "main instance", i.e. `daps.aisec.fraunhofer.de` as much as possible.
I assume that there might have been old certificates in use or something else went wrong, but great it works for you now.
